// Every table's field definitions.
// type: text | number | boolean | uuid | textarea | json | array | select | datetime
// fk: { table, labelField } — renders a dropdown populated from the referenced table
// readonly: shown but not editable (auto-generated fields)
// hidden: not shown in forms at all

export const TABLES = {
  products: {
    label: 'Products',
    icon: '🛍️',
    primaryKey: 'id',
    displayField: 'name',
    fields: [
      { key: 'id',               label: 'ID',               type: 'text',     readonly: true },
      { key: 'name',             label: 'Name',             type: 'text',     required: true },
      { key: 'slug',             label: 'Slug',             type: 'text',     required: true },
      { key: 'description',      label: 'Description',      type: 'textarea' },
      { key: 'price',            label: 'Price (₦)',         type: 'number',   required: true },
      { key: 'compare_price',    label: 'Compare Price (₦)', type: 'number' },
      { key: 'currency',         label: 'Currency',         type: 'text',     defaultValue: 'NGN' },
      { key: 'category_id',      label: 'Category',         type: 'uuid',     fk: { table: 'categories', labelField: 'name' } },
      { key: 'size_chart_id',    label: 'Size Chart',       type: 'uuid',     fk: { table: 'size_charts', labelField: 'name' } },
      { key: 'is_active',        label: 'Active',           type: 'boolean',  defaultValue: true },
      { key: 'is_featured',      label: 'Featured',         type: 'boolean',  defaultValue: false },
      { key: 'is_new_in',        label: 'New In',           type: 'boolean',  defaultValue: false },
      { key: 'tags',             label: 'Tags (comma separated)', type: 'array' },
      { key: 'meta_title',       label: 'Meta Title',       type: 'text' },
      { key: 'meta_desc',        label: 'Meta Description', type: 'textarea' },
      { key: 'content_sections', label: 'Content Sections', type: 'json' },
      { key: 'created_at',       label: 'Created At',       type: 'datetime', readonly: true },
      { key: 'updated_at',       label: 'Updated At',       type: 'datetime', readonly: true },
    ],
  },

  categories: {
    label: 'Categories',
    icon: '📂',
    primaryKey: 'id',
    displayField: 'name',
    fields: [
      { key: 'id',          label: 'ID',          type: 'text',    readonly: true },
      { key: 'name',        label: 'Name',        type: 'text',    required: true },
      { key: 'slug',        label: 'Slug',        type: 'text',    required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image_url',   label: 'Image URL',   type: 'text' },
      { key: 'parent_id',   label: 'Parent Category', type: 'uuid', fk: { table: 'categories', labelField: 'name' } },
      { key: 'sort_order',  label: 'Sort Order',  type: 'number',  defaultValue: 0 },
      { key: 'is_active',   label: 'Active',      type: 'boolean', defaultValue: true },
      { key: 'created_at',  label: 'Created At',  type: 'datetime', readonly: true },
    ],
  },

  collections: {
    label: 'Collections',
    icon: '✨',
    primaryKey: 'id',
    displayField: 'name',
    fields: [
      { key: 'id',          label: 'ID',          type: 'text',    readonly: true },
      { key: 'name',        label: 'Name',        type: 'text',    required: true },
      { key: 'slug',        label: 'Slug',        type: 'text',    required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image_url',   label: 'Image URL',   type: 'text' },
      { key: 'is_active',   label: 'Active',      type: 'boolean', defaultValue: true },
      { key: 'sort_order',  label: 'Sort Order',  type: 'number',  defaultValue: 0 },
      { key: 'created_at',  label: 'Created At',  type: 'datetime', readonly: true },
    ],
  },

  collection_products: {
    label: 'Collection → Products',
    icon: '🔗',
    primaryKey: null,
    displayField: 'collection_id',
    compositePK: ['collection_id', 'product_id'],
    fields: [
      { key: 'collection_id', label: 'Collection', type: 'uuid', required: true, fk: { table: 'collections', labelField: 'name' } },
      { key: 'product_id',    label: 'Product',    type: 'uuid', required: true, fk: { table: 'products', labelField: 'name' } },
      { key: 'sort_order',    label: 'Sort Order', type: 'number', defaultValue: 0 },
    ],
  },

  size_charts: {
    label: 'Size Charts',
    icon: '📏',
    primaryKey: 'id',
    displayField: 'name',
    fields: [
      { key: 'id',          label: 'ID',          type: 'text',    readonly: true },
      { key: 'name',        label: 'Name',        type: 'text',    required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'headers',     label: 'Headers (comma separated)', type: 'array' },
      { key: 'rows',        label: 'Rows (JSON array of arrays)', type: 'json' },
      { key: 'created_at',  label: 'Created At',  type: 'datetime', readonly: true },
    ],
  },

  orders: {
    label: 'Orders',
    icon: '📦',
    primaryKey: 'id',
    displayField: 'order_number',
    readOnly: true,
    fields: [
      { key: 'id',               label: 'ID',              type: 'text',     readonly: true },
      { key: 'order_number',     label: 'Order #',         type: 'text',     readonly: true },
      { key: 'user_id',          label: 'Customer',        type: 'uuid',     fk: { table: 'profiles', labelField: 'email' } },
      { key: 'status',           label: 'Status',          type: 'select',   options: ['pending','paid','processing','shipped','delivered','cancelled','refunded'] },
      { key: 'subtotal',         label: 'Subtotal (₦)',    type: 'number',   readonly: true },
      { key: 'shipping_fee',     label: 'Shipping (₦)',    type: 'number',   readonly: true },
      { key: 'discount_amount',  label: 'Discount (₦)',    type: 'number',   readonly: true },
      { key: 'total',            label: 'Total (₦)',       type: 'number',   readonly: true },
      { key: 'payment_status',   label: 'Payment Status',  type: 'select',   options: ['pending','paid','failed','refunded'] },
      { key: 'payment_method',   label: 'Payment Method',  type: 'text' },
      { key: 'payment_provider', label: 'Payment Provider', type: 'text' },
      { key: 'payment_ref',      label: 'Payment Ref',     type: 'text' },
      { key: 'paid_at',          label: 'Paid At',         type: 'datetime' },
      { key: 'shipping_name',    label: 'Ship To Name',    type: 'text' },
      { key: 'shipping_phone',   label: 'Ship Phone',      type: 'text' },
      { key: 'shipping_address1', label: 'Address Line 1', type: 'text' },
      { key: 'shipping_address2', label: 'Address Line 2', type: 'text' },
      { key: 'shipping_city',    label: 'City',            type: 'text' },
      { key: 'shipping_state',   label: 'State',           type: 'text' },
      { key: 'shipping_country', label: 'Country',         type: 'text' },
      { key: 'shipping_carrier', label: 'Carrier',         type: 'text' },
      { key: 'tracking_number',  label: 'Tracking #',      type: 'text' },
      { key: 'shipped_at',       label: 'Shipped At',      type: 'datetime' },
      { key: 'delivered_at',     label: 'Delivered At',    type: 'datetime' },
      { key: 'coupon_code',      label: 'Coupon Code',     type: 'text' },
      { key: 'notes',            label: 'Notes',           type: 'textarea' },
      { key: 'created_at',       label: 'Created At',      type: 'datetime', readonly: true },
    ],
  },

  order_items: {
    label: 'Order Items',
    icon: '🧾',
    primaryKey: 'id',
    displayField: 'product_name',
    fields: [
      { key: 'id',            label: 'ID',           type: 'text',   readonly: true },
      { key: 'order_id',      label: 'Order',        type: 'uuid',   required: true, fk: { table: 'orders', labelField: 'order_number' } },
      { key: 'variant_id',    label: 'Variant',      type: 'uuid',   fk: { table: 'product_variants', labelField: 'sku' } },
      { key: 'product_name',  label: 'Product Name', type: 'text',   required: true },
      { key: 'variant_size',  label: 'Size',         type: 'text' },
      { key: 'variant_color', label: 'Color',        type: 'text' },
      { key: 'sku',           label: 'SKU',          type: 'text' },
      { key: 'quantity',      label: 'Quantity',     type: 'number', required: true },
      { key: 'unit_price',    label: 'Unit Price',   type: 'number', required: true },
      { key: 'total_price',   label: 'Total Price',  type: 'number', required: true },
      { key: 'image_url',     label: 'Image URL',    type: 'text' },
      { key: 'created_at',    label: 'Created At',   type: 'datetime', readonly: true },
    ],
  },

  profiles: {
    label: 'Profiles',
    icon: '👤',
    primaryKey: 'id',
    displayField: 'email',
    fields: [
      { key: 'id',         label: 'ID',         type: 'text',   readonly: true },
      { key: 'email',      label: 'Email',      type: 'text',   required: true },
      { key: 'full_name',  label: 'Full Name',  type: 'text' },
      { key: 'phone',      label: 'Phone',      type: 'text' },
      { key: 'role',       label: 'Role',       type: 'select', options: ['customer', 'admin'], defaultValue: 'customer' },
      { key: 'avatar_url', label: 'Avatar URL', type: 'text' },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
      { key: 'updated_at', label: 'Updated At', type: 'datetime', readonly: true },
    ],
  },

  addresses: {
    label: 'Addresses',
    icon: '📍',
    primaryKey: 'id',
    displayField: 'full_name',
    fields: [
      { key: 'id',            label: 'ID',            type: 'text',    readonly: true },
      { key: 'user_id',       label: 'User',          type: 'uuid',    required: true, fk: { table: 'profiles', labelField: 'email' } },
      { key: 'label',         label: 'Label',         type: 'text' },
      { key: 'full_name',     label: 'Full Name',     type: 'text',    required: true },
      { key: 'phone',         label: 'Phone',         type: 'text',    required: true },
      { key: 'address_line1', label: 'Address Line 1', type: 'text',   required: true },
      { key: 'address_line2', label: 'Address Line 2', type: 'text' },
      { key: 'city',          label: 'City',          type: 'text',    required: true },
      { key: 'state',         label: 'State',         type: 'text',    required: true },
      { key: 'country',       label: 'Country',       type: 'text',    defaultValue: 'Nigeria' },
      { key: 'postal_code',   label: 'Postal Code',   type: 'text' },
      { key: 'is_default',    label: 'Default',       type: 'boolean', defaultValue: false },
      { key: 'created_at',    label: 'Created At',    type: 'datetime', readonly: true },
    ],
  },

  carts: {
    label: 'Carts',
    icon: '🛒',
    primaryKey: 'id',
    displayField: 'id',
    fields: [
      { key: 'id',         label: 'ID',         type: 'text', readonly: true },
      { key: 'user_id',    label: 'User',       type: 'uuid', fk: { table: 'profiles', labelField: 'email' } },
      { key: 'session_id', label: 'Session ID', type: 'text' },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
      { key: 'updated_at', label: 'Updated At', type: 'datetime', readonly: true },
    ],
  },

  cart_items: {
    label: 'Cart Items',
    icon: '🛒',
    primaryKey: 'id',
    displayField: 'id',
    fields: [
      { key: 'id',         label: 'ID',         type: 'text',   readonly: true },
      { key: 'cart_id',    label: 'Cart',       type: 'uuid',   required: true, fk: { table: 'carts', labelField: 'id' } },
      { key: 'variant_id', label: 'Variant',    type: 'uuid',   required: true, fk: { table: 'product_variants', labelField: 'sku' } },
      { key: 'quantity',   label: 'Quantity',   type: 'number', required: true, defaultValue: 1 },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
    ],
  },

  reviews: {
    label: 'Reviews',
    icon: '⭐',
    primaryKey: 'id',
    displayField: 'title',
    fields: [
      { key: 'id',          label: 'ID',          type: 'text',    readonly: true },
      { key: 'product_id',  label: 'Product',     type: 'uuid',    required: true, fk: { table: 'products', labelField: 'name' } },
      { key: 'user_id',     label: 'User',        type: 'uuid',    required: true, fk: { table: 'profiles', labelField: 'email' } },
      { key: 'order_id',    label: 'Order',       type: 'uuid',    fk: { table: 'orders', labelField: 'order_number' } },
      { key: 'rating',      label: 'Rating (1-5)', type: 'number', required: true },
      { key: 'title',       label: 'Title',       type: 'text' },
      { key: 'body',        label: 'Body',        type: 'textarea' },
      { key: 'is_approved', label: 'Approved',    type: 'boolean', defaultValue: false },
      { key: 'created_at',  label: 'Created At',  type: 'datetime', readonly: true },
    ],
  },

  wishlists: {
    label: 'Wishlists',
    icon: '❤️',
    primaryKey: 'id',
    displayField: 'id',
    fields: [
      { key: 'id',         label: 'ID',         type: 'text', readonly: true },
      { key: 'user_id',    label: 'User',       type: 'uuid', required: true, fk: { table: 'profiles', labelField: 'email' } },
      { key: 'product_id', label: 'Product',    type: 'uuid', required: true, fk: { table: 'products', labelField: 'name' } },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
    ],
  },

  coupons: {
    label: 'Coupons',
    icon: '🎟️',
    primaryKey: 'id',
    displayField: 'code',
    fields: [
      { key: 'id',             label: 'ID',             type: 'text',    readonly: true },
      { key: 'code',           label: 'Code',           type: 'text',    required: true },
      { key: 'description',    label: 'Description',    type: 'textarea' },
      { key: 'discount_type',  label: 'Discount Type',  type: 'select',  options: ['percentage', 'fixed'], required: true },
      { key: 'discount_value', label: 'Discount Value', type: 'number',  required: true },
      { key: 'minimum_order',  label: 'Minimum Order (₦)', type: 'number', defaultValue: 0 },
      { key: 'max_uses',       label: 'Max Uses (blank = unlimited)', type: 'number' },
      { key: 'used_count',     label: 'Used Count',     type: 'number',  readonly: true, defaultValue: 0 },
      { key: 'expires_at',     label: 'Expires At',     type: 'datetime' },
      { key: 'is_active',      label: 'Active',         type: 'boolean', defaultValue: true },
      { key: 'created_at',     label: 'Created At',     type: 'datetime', readonly: true },
    ],
  },

  newsletter_subscribers: {
    label: 'Newsletter',
    icon: '📧',
    primaryKey: 'id',
    displayField: 'email',
    fields: [
      { key: 'id',            label: 'ID',           type: 'text',    readonly: true },
      { key: 'email',         label: 'Email',        type: 'text',    required: true },
      { key: 'is_active',     label: 'Active',       type: 'boolean', defaultValue: true },
      { key: 'subscribed_at', label: 'Subscribed At', type: 'datetime', readonly: true },
    ],
  },

  product_variants: {
    label: 'Product Variants',
    icon: '🎨',
    primaryKey: 'id',
    displayField: 'sku',
    fields: [
      { key: 'id', label: 'ID', type: 'text', readonly: true },
      { key: 'product_id', label: 'Product', type: 'uuid', required: true, fk: { table: 'products', labelField: 'name' } },
      { key: 'size', label: 'Size', type: 'text' },
      { key: 'color', label: 'Color Name', type: 'text' },
      { key: 'color_hex', label: 'Color Hex Values (comma separated)', type: 'array' },
      { key: 'option_name', label: 'Option Name', type: 'text' },
      { key: 'option_value', label: 'Option Value', type: 'text' },
      { key: 'sku', label: 'SKU', type: 'text' },
      { key: 'stock', label: 'Stock', type: 'number', required: true, defaultValue: 0 },
      { key: 'price', label: 'Price Override (₦)', type: 'number' },
      { key: 'is_active', label: 'Active', type: 'boolean', defaultValue: true },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
    ],
  },

  product_images: {
    label: 'Product Images',
    icon: '🖼️',
    primaryKey: 'id',
    displayField: 'url',
    fields: [
      { key: 'id', label: 'ID', type: 'text', readonly: true },
      { key: 'product_id', label: 'Product', type: 'uuid', required: true, fk: { table: 'products', labelField: 'name' } },
      { key: 'variant_id', label: 'Variant (optional)', type: 'uuid', fk: { table: 'product_variants', labelField: 'sku' } },
      { key: 'url', label: 'Image URL', type: 'text', required: true },
      { key: 'alt_text', label: 'Alt Text', type: 'text' },
      { key: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
      { key: 'is_primary', label: 'Primary Image', type: 'boolean', defaultValue: false },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
    ],
  },
}

export const TABLE_GROUPS = [
  {
    label: 'Catalogue',
    tables: ['products', 'categories', 'collections', 'collection_products', 'size_charts'],
  },
  {
    label: 'Orders',
    tables: ['orders', 'order_items'],
  },
  {
    label: 'Customers',
    tables: ['profiles', 'addresses', 'carts', 'cart_items', 'wishlists', 'reviews'],
  },
  {
    label: 'Marketing',
    tables: ['coupons', 'newsletter_subscribers'],
  },
]
