export const productsTables = {
  products: {
    label: 'Products',
    icon: '🛍️',
    primaryKey: 'id',
    displayField: 'name',
    fields: [
      { key: 'id', label: 'ID', type: 'text', readonly: true },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'price', label: 'Price (₦)', type: 'number', required: true },
      { key: 'compare_price', label: 'Compare Price (₦)', type: 'number' },
      { key: 'currency', label: 'Currency', type: 'text', defaultValue: 'NGN' },
      { key: 'category_id', label: 'Category', type: 'uuid', fk: { table: 'categories', labelField: 'name' } },
      { key: 'size_chart_id', label: 'Size Chart', type: 'uuid', fk: { table: 'size_charts', labelField: 'name' } },
      { key: 'is_active', label: 'Active', type: 'boolean', defaultValue: true },
      { key: 'is_featured', label: 'Featured', type: 'boolean', defaultValue: false },
      { key: 'is_new_in', label: 'New In', type: 'boolean', defaultValue: false },
      { key: 'tags', label: 'Tags (comma separated)', type: 'array' },
      { key: 'meta_title', label: 'Meta Title', type: 'text' },
      { key: 'meta_desc', label: 'Meta Description', type: 'textarea' },
      { key: 'content_sections', label: 'Content Sections', type: 'json' },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
      { key: 'updated_at', label: 'Updated At', type: 'datetime', readonly: true },
    ],
  },

  product_variants: {
    label: 'Product Variants',
    icon: '🎨',
    primaryKey: 'id',
    displayField: 'sku',
    fields: [
      { key: 'id', label: 'ID', type: 'text', readonly: true },
      { key: 'product_id', label: 'Product', type: 'uuid', required: true, fk: { table: 'products', labelField: 'name' } },
      { key: 'size', label: 'Size', type: 'text' },
      { key: 'color', label: 'Color Name', type: 'text' },
      { key: 'color_hex', label: 'Color Hex Values (comma separated)', type: 'array' },
      { key: 'option_name', label: 'Option Name', type: 'text' },
      { key: 'option_value', label: 'Option Value', type: 'text' },
      { key: 'sku', label: 'SKU', type: 'text' },
      { key: 'stock', label: 'Stock', type: 'number', required: true, defaultValue: 0 },
      { key: 'price', label: 'Price Override (₦)', type: 'number' },
      { key: 'is_active', label: 'Active', type: 'boolean', defaultValue: true },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
    ],
  },

  product_images: {
    label: 'Product Images',
    icon: '🖼️',
    primaryKey: 'id',
    displayField: 'url',
    fields: [
      { key: 'id', label: 'ID', type: 'text', readonly: true },
      { key: 'product_id', label: 'Product', type: 'uuid', required: true, fk: { table: 'products', labelField: 'name' } },
      { key: 'variant_id', label: 'Variant (optional)', type: 'uuid', fk: { table: 'product_variants', labelField: 'sku' } },
      { key: 'url', label: 'Image URL', type: 'text', required: true },
      { key: 'alt_text', label: 'Alt Text', type: 'text' },
      { key: 'sort_order', label: 'Sort Order', type: 'number', defaultValue: 0 },
      { key: 'is_primary', label: 'Primary Image', type: 'boolean', defaultValue: false },
      { key: 'created_at', label: 'Created At', type: 'datetime', readonly: true },
    ],
  },
}
